name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]  # veya master, ana dalınızın adına göre değişebilir

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # GitHub Pages'e yazma izni ekleyelim
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        persist-credentials: false

    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: .  # Dağıtılacak klasör (projenizin kök dizini)
        token: ${{ secrets.GITHUB_TOKEN }}  # GitHub tarafından otomatik sağlanan token
        clean: true  # Önceki dağıtımları temizle
        clean-exclude: |
          .nojekyll